# -*- coding: utf-8 -*-
"""Single source of truth for action types: values, copy in both languages, evidence."""

BMJ = ("Spiegelhalter, BMJ 2012;345:e8223", "https://pubmed.ncbi.nlm.nih.gov/23247978/")
CONV = ("Microlives table, The Conversation",
        "https://cdn.theconversation.com/assets_for_articles/2017-12-22-microlife-table.pdf")
GUIDE = ("General reference. The number is mine, not from it",
         "https://www.health.harvard.edu/staying-healthy")

EST_EN = ("The size was set by me to sit sensibly beside neighbouring rows, not taken "
          "from a study. The direction of the effect is widely accepted, the magnitude is not")
EST_RU = ("Величина назначена мной по порядку соседних строк, а не взята из работы. "
          "Направление эффекта общепринято, размер — нет")

# id, coefficient expr, emoji, keywords, confidence, source, dosing-or-None
# label/exposure/basis/caveat as (en, ru)
ACTIONS = [
 dict(id="smoke", coef="Coefficients.SMOKE", emoji="🚬", conf="STRONG", src=BMJ,
   kw="сигарета курить сижка табак дым smoke cigarette",
   label=("Smoked", "Покурил"),
   exposure=("Two cigarettes a day = one microlife", "Две сигареты в день = одна микрожизнь"),
   basis=("Microlives table; the link between smoking and mortality is among the firmest in all of epidemiology",
          "Таблица микрожизней; связь курения со смертностью — одна из самых твёрдых в эпидемиологии вообще"),
   caveat=("The figure is averaged over a population and over a smoker's whole life. One particular cigarette does not literally deduct anything",
           "Величина усреднена по популяции и по всей жизни курящего. Одна конкретная сигарета ничего не «списывает» буквально")),
 dict(id="drink", coef="Coefficients.DRINK", emoji="🍷", conf="CHOSEN", src=BMJ,
   kw="алкоголь бокал пиво вино бухло drink alcohol beer wine",
   label=("Had a drink", "Выпил"),
   exposure=("One drink (10 g of alcohol)", "Одна доза (10 г спирта)"),
   basis=("Your value. The source is non-linear: the first drink of the day is +1 microlife, each of the next up to six goes negative",
          "Значение из твоего ТЗ. В источнике алкоголь нелинеен: первая доза за день +1 микрожизнь, каждая следующая до шести — в минус"),
   caveat=("The norm now restores the source's shape: the first drink of the day helps, the rest cost",
           "Норма теперь возвращает форму источника: первая доза за день в плюс, остальные в минус"),
   dosing=("DAY", 1, "30", "Coefficients.DRINK")),
 dict(id="rest", coef="Coefficients.REST", emoji="🧘", conf="CHOSEN", src=BMJ,
   kw="отдых дыхание медитация пауза rest breathe meditation",
   label=("Rested", "Отдохнул"),
   exposure=("A deliberate pause or breathing practice", "Осознанная пауза или дыхательная практика"),
   basis=("Your value", "Значение из твоего ТЗ"),
   caveat=("No source has a row for deliberate rest. This is a motivational button, not a measured effect",
           "Строки про осознанный отдых нет ни в одном из источников. Это мотивационная кнопка, а не измеренный эффект")),
 dict(id="workout", coef="Coefficients.WORKOUT", emoji="🏋", conf="CHOSEN", src=BMJ,
   kw="спорт зал качалка тренировка workout gym sport training",
   label=("Workout", "Тренировка"),
   exposure=("First 20 minutes of moderate exercise, HR 0.81", "Первые 20 минут умеренной нагрузки, HR 0.81"),
   basis=("Your value. The source gives twice as much: the first 20 minutes are 2 microlives (+60), the next forty add up to one more",
          "Значение из твоего ТЗ. Источник даёт вдвое больше: первые 20 минут = 2 микрожизни (+60), следующие сорок — ещё до одной"),
   caveat=("You are undervaluing exercise twofold here. Set 60 to match the source",
           "Здесь ты недооцениваешь тренировку вдвое. Поставь 60, чтобы совпало с источником")),
 dict(id="sleep_short", coef="Coefficients.SLEEP_SHORT", emoji="🥱", conf="STRONG",
   src=("Sleep and mortality meta-analysis, GeroScience 2025",
        "https://link.springer.com/article/10.1007/s11357-025-01592-y"),
   kw="сон недосып мало спал не выспался sleep deprivation",
   label=("Slept under 7 h", "Недосып, меньше 7 ч"),
   exposure=("Under 7 hours a night against the 7–8 reference", "Меньше 7 часов сна за ночь против нормы 7–8"),
   basis=("Meta-analysis, HR 1.14 → −1.43 microlives a day by the paper's formula. The curve is U-shaped: 9+ hours is worse still, HR 1.34",
          "Мета-анализ, HR 1.14 → −1.43 микрожизни в день по формуле статьи. Связь U-образная: 9+ часов ещё хуже, HR 1.34"),
   caveat=("There is deliberately no «slept well» button: 7–8 hours is the reference point, not a bonus. Long sleep is almost certainly reverse causation — sick people sleep more",
           "Кнопки «выспался» нет намеренно: 7–8 часов — это точка отсчёта, а не бонус. Длинный сон почти наверняка обратная причинность — больные спят дольше")),
 dict(id="late_night", coef="Coefficients.LATE_NIGHT", emoji="🦉", conf="MODERATE",
   src=("Knutson & von Schantz, Chronobiology International 2018",
        "https://www.tandfonline.com/doi/full/10.1080/07420528.2018.1454458"),
   kw="сова поздно ночь режим сдвиг хронотип owl chronotype",
   label=("Went to bed after 2 am", "Лёг после 2 ночи"),
   exposure=("Definite evening chronotype against morning", "Выраженный вечерний хронотип против утреннего"),
   basis=("UK Biobank, 433,268 people, 6.5 years. HR 1.10 → −1.04 microlives a day by the paper's formula",
          "UK Biobank, 433 268 человек, 6.5 лет. HR 1.10 → −1.04 микрожизни в день по формуле статьи"),
   caveat=("They measured self-described «owl or lark», not bedtime. And it is more about clashing with your work schedule than about the chronotype itself: later working hours remove part of the harm",
           "Мерили самоопределение «сова или жаворонок», а не время отбоя. И это скорее про рассогласование с графиком работы, чем про сам хронотип: более поздняя работа часть вреда снимает")),
 dict(id="social", coef="Coefficients.SOCIAL", emoji="👥", conf="STRONG",
   src=("Holt-Lunstad et al., Perspectives on Psychological Science 2015",
        "https://journals.sagepub.com/doi/full/10.1177/1745691614568352"),
   kw="друзья общение встреча люди социальное social friends",
   label=("Time with people", "Живое общение"),
   exposure=("Not being socially isolated, per day", "Отсутствие социальной изоляции, за день"),
   basis=("Meta-analysis: 148 studies, 308,849 people. Taken from OR 1.29 for isolation → +2.78 microlives a day. The «strong versus weak ties» contrast gives 1.50 but it is an extreme one and would overstate a single button",
          "Мета-анализ: 148 работ, 308 849 человек. Взят OR 1.29 для изоляции → +2.78 микрожизни в день. Контраст «сильные против слабых связей» даёт 1.50, но он крайний и для одной кнопки завышал бы"),
   caveat=("The largest plus in the list, and that is not a mistake: by effect size loneliness is comparable to smoking. But one tap does not move a person from isolated to connected",
           "Самый большой плюс в списке — и это не ошибка: по силе связи одиночество сопоставимо с курением. Но одно нажатие не переводит человека из изолированных в общительные")),
 dict(id="sex", coef="Coefficients.SEX", emoji="❤️", conf="WEAK",
   src=("Davey Smith et al., BMJ 1997 — Sex and death", "https://pubmed.ncbi.nlm.nih.gov/9448525/"),
   kw="секс интим близость sex intimacy",
   label=("Sex", "Секс"),
   exposure=("+100 orgasms a year, men aged 45–59", "+100 оргазмов в год, мужчины 45–59 лет"),
   basis=("Caerphilly, 918 men, 10 years. OR 0.64 → roughly +530 minutes per event by the formula. That is implausibly large, so a conservative figure at the level of a workout was taken instead",
          "Caerphilly, 918 мужчин, 10 лет. OR 0.64 → по формуле около +530 минут за раз. Это неправдоподобно много, поэтому взята консервативная оценка на уровне тренировки"),
   caveat=("The number is mine, not the study's. Small and old sample (1997), self-reported, and almost certainly reverse causation: ill people have less sex, not the other way round",
           "Число выбрано мной, а не работой. Выборка мелкая и старая (1997), самоотчёт, и почти наверняка обратная причинность: у больных людей секса меньше, а не наоборот")),
 dict(id="walk", coef="Coefficients.WALK", emoji="🚶", conf="MODERATE", src=CONV,
   kw="ходьба прогулка шаги walk walking steps",
   label=("A kilometre on foot", "Километр пешком"),
   exposure=("One kilometre of walking", "Километр ходьбы"),
   basis=("Extended microlives table, +0.4 microlives per kilometre", "Расширенная таблица микрожизней, +0.4 микрожизни на километр"),
   caveat=("This row is not in the BMJ paper itself, only in the retelling. It is consistent in order of magnitude with the main exercise row",
           "В самой статье BMJ этой строки нет, только в пересказе. С основной строкой про нагрузку согласуется по порядку величины")),
 dict(id="nature", coef="Coefficients.NATURE", emoji="🌲", conf="MODERATE",
   src=("Rojas-Rueda et al., Lancet Planetary Health 2019",
        "https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(19)30215-3/fulltext"),
   kw="природа лес парк зелень дача nature green outdoors",
   label=("A day outdoors", "День на природе"),
   exposure=("+0.1 NDVI of greenness within 500 m of home", "+0.1 NDVI зелени в радиусе 500 м от дома"),
   basis=("Meta-analysis of cohorts, HR 0.96 → +0.45 microlives a day", "Мета-анализ когорт, HR 0.96 → +0.45 микрожизни в день"),
   caveat=("They measured greenness around housing, not weekend trips. A one-off outing is not the same thing, so the figure is more symbolic than measured",
           "Мерили зелень вокруг жилья, а не вылазки на выходных. Разовый выезд этому не равен, так что величина скорее символическая")),
 dict(id="air_pollution", coef="Coefficients.AIR_POLLUTION", emoji="🏭", conf="MODERATE", src=BMJ,
   kw="смог воздух грязь пыль выхлопы pm25 air pollution smog",
   label=("A day in smog", "День в смоге"),
   exposure=("Living in Mexico City versus London, −0.6 microlives a day", "Жизнь в Мехико против Лондона, −0.6 микрожизни в день"),
   basis=("A row from the microlives table", "Строка из таблицы микрожизней"),
   caveat=("Important: a big city by itself is a plus, not a minus, in developed countries — city dwellers outlive rural ones and the gap is widening. The air is worse, but access to healthcare outweighs it. This button is about smog, not about cities",
           "Важно: сам по себе большой город в развитых странах в плюсе, а не в минусе — горожане живут дольше сельских, и разрыв растёт. Воздух хуже, но доступ к медицине перевешивает. Эта кнопка про смог, а не про город")),
 dict(id="coffee", coef="Coefficients.COFFEE", emoji="☕", conf="MODERATE", src=BMJ,
   kw="кофе эспрессо капучино coffee espresso",
   label=("Coffee", "Кофе"),
   exposure=("2–3 cups a day, HR 0.90", "2–3 чашки в день, HR 0.90"),
   basis=("The table gives +1 microlife for 2–3 cups, hence a third of that per cup", "Таблица даёт +1 микрожизнь за 2–3 чашки, отсюда треть на чашку"),
   caveat=("Observational. Coffee is drunk by the employed and socially active — part of the effect is surely theirs, not the coffee's",
           "Наблюдательное. Кофе пьют работающие и социально активные — часть эффекта наверняка их, а не кофе"),
   dosing=("DAY", 3, "Coefficients.COFFEE", "0")),
 dict(id="vegetables", coef="Coefficients.VEGETABLES", emoji="🥦", conf="WEAK", src=BMJ,
   kw="овощи салат фрукты зелень vegetables fruit salad",
   label=("Vegetables, one serving", "Овощи, порция"),
   exposure=("≥5 servings a day, HR 0.66 in men", "≥5 порций в день, HR 0.66 у мужчин"),
   basis=("The table gives +4 microlives for FIVE servings; divided by five here", "Таблица даёт +4 микрожизни за ПЯТЬ порций, здесь поделено на пять"),
   caveat=("The shakiest row in the table. They measured not servings but blood vitamin C above 50 nmol/L — a marker that also flags people who live better overall. A third off mortality from vegetables is implausible as a causal effect",
           "Самая шаткая строка в таблице. Мерили не порции, а витамин C в крови выше 50 нмоль/л — маркер, который заодно метит тех, кто в целом лучше живёт. Минус треть смертности от овощей как причинный эффект неправдоподобен"),
   dosing=("DAY", 5, "Coefficients.VEGETABLES", "0")),
 dict(id="red_meat", coef="Coefficients.RED_MEAT", emoji="🥩", conf="MODERATE",
   src=("Pan et al., Arch Intern Med 2012", "https://pmc.ncbi.nlm.nih.gov/articles/PMC3712342"),
   kw="мясо стейк говядина свинина meat steak beef pork",
   label=("Red meat, 85 g", "Красное мясо, 85 г"),
   exposure=("One 85 g (3 oz) serving a day, lifelong from age 35", "Одна порция 85 г (3 унции) в день, пожизненно с 35 лет"),
   basis=("Harvard cohorts, 121,342 people. HR 1.13 for unprocessed, 1.20 for processed", "Гарвардские когорты, 121 342 человека. HR 1.13 для необработанного, 1.20 для обработанного"),
   caveat=("The serving is smaller than it sounds — about one burger patty. The weekly norm matters here: the studies measure an EXTRA serving on top of habit, so meat a couple of times a week is the baseline, not a sin",
           "Порция меньше, чем кажется — примерно котлета для бургера. Норма за неделю здесь и важна: исследования меряют ЛИШНЮЮ порцию сверх привычного, так что мясо пару раз в неделю — это фон, а не грех"),
   dosing=("WEEK", 3, "0", "Coefficients.RED_MEAT")),
 dict(id="fast_food", coef="Coefficients.FAST_FOOD", emoji="🍔", conf="MODERATE", src=BMJ,
   kw="бургер фастфуд макдак картошка шаурма burger fast food",
   label=("Fast food", "Фастфуд"),
   exposure=("One burger", "Один бургер"),
   basis=("Named in the paper's text alongside a serving of meat and two cigarettes — one microlife", "Названо в тексте статьи в одном ряду с порцией мяса и двумя сигаретами — одна микрожизнь"),
   caveat=("There is no separate table row, only a mention in the text. It is most likely the red meat row in other words",
           "Отдельной строки в таблице нет, только упоминание в тексте. Скорее всего это та же строка про красное мясо другими словами"),
   dosing=("WEEK", 1, "0", "Coefficients.FAST_FOOD")),
 dict(id="tv", coef="Coefficients.TV", emoji="📺", conf="MODERATE", src=BMJ,
   kw="телевизор сериал ютуб скроллинг лежал tv screen scrolling",
   label=("An hour of screen time", "Час у экрана"),
   exposure=("Two hours of television a day, HR 1.08", "Два часа телевизора в день, HR 1.08"),
   basis=("The table gives −1 microlife for two hours, hence half per hour", "Таблица даёт −1 микрожизнь за два часа, отсюда половина на час"),
   caveat=("They measured television, not screens in general. The harm is attributed to sitting, so desk work probably counts the same",
           "Мерили телевизор, а не экран вообще. Вред приписывают сидению, так что работа за столом, вероятно, считается так же"),
   dosing=("DAY", 2, "0", "Coefficients.TV")),
 dict(id="pet", coef="Coefficients.PET", emoji="🐕", conf="WEAK", src=CONV,
   kw="кот собака питомец гулял с собакой pet dog cat",
   label=("Time with a pet", "С питомцем"),
   exposure=("A day with a cat or dog", "День с кошкой или собакой"),
   basis=("A row from the extended table, +1 microlife", "Строка из расширенной таблицы, +1 микрожизнь"),
   caveat=("This row is not in the BMJ paper at all, and no study is cited for it. Trust it less than the rest",
           "В статье BMJ этой строки нет вообще, и ссылки на исследование при ней не приведено. Доверия меньше, чем к остальным")),
 dict(id="active_mind", coef="Coefficients.ACTIVE_MIND", emoji="🧠", conf="WEAK", src=CONV,
   kw="мозг учёба чтение книга задача mind study learning",
   label=("Studied", "Учился"),
   exposure=("A day of mental exertion", "День умственной нагрузки"),
   basis=("A row from the extended table, +4 microlives", "Строка из расширенной таблицы, +4 микрожизни"),
   caveat=("Not in the BMJ paper, no study cited. And the figure is huge — second largest in the list. Too early to trust",
           "В статье BMJ этой строки нет, ссылки на исследование не приведено. При этом величина огромная — вторая по размеру в списке. Верить рано")),
 dict(id="water", coef="Coefficients.WATER", emoji="💧", conf="NONE",
   src=("Dmitrieva et al., eBioMedicine 2023",
        "https://www.thelancet.com/journals/ebiom/article/PIIS2352-3964(22)00586-2/fulltext"),
   kw="вода стакан пить гидратация water hydration",
   label=("A glass of water", "Стакан воды"),
   exposure=("Serum sodium in the upper normal range, 11,255 people, 30 years", "Натрий в крови в верхней части нормы, 11 255 человек, 30 лет"),
   basis=("Zero is the result of checking, not a placeholder", "Ноль — это результат проверки, а не заглушка"),
   caveat=("The famous hydration study measured sodium in blood, not water drunk. That «drinking more water» extends life has not been shown. Drink when thirsty",
           "Громкое исследование про гидратацию мерило натрий в крови, а не выпитую воду. Что «пить больше воды» продлевает жизнь — не показано. Пей по жажде")),
 dict(id="multivitamin", coef="Coefficients.MULTIVITAMIN", emoji="💊", conf="NONE",
   src=("Loftfield et al., JAMA Network Open 2024",
        "https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2820369"),
   kw="витамины бады таблетки добавки vitamin supplement",
   label=("Multivitamins", "Мультивитамины"),
   exposure=("Daily multivitamin use", "Ежедневный приём мультивитаминов"),
   basis=("390,124 healthy people, over 20 years of follow-up. No mortality benefit — not all-cause, not cancer, not heart", "390 124 здоровых человека, более 20 лет наблюдения. Выигрыша по смертности нет — ни общей, ни от рака, ни от сердца"),
   caveat=("This is about healthy people and about extending life. A proven deficiency of a specific vitamin is an entirely different matter",
           "Это про здоровых людей и про продление жизни. При доказанном дефиците конкретного витамина речь совсем о другом")),
]

ACTIONS += [
 dict(id="sauna", coef="Coefficients.SAUNA", emoji="🧖", conf="MODERATE",
   src=("Laukkanen et al., JAMA Internal Medicine 2015",
        "https://jamanetwork.com/journals/jamainternalmedicine/article-abstract/2448449"),
   kw="сауна баня парная хамам sauna steam",
   label=("Sauna", "Сауна или баня"),
   exposure=("4–7 sessions a week against one, HR 0.60", "4–7 посещений в неделю против одного, HR 0.60"),
   basis=("Kuopio cohort, 2,315 men, 20.7 years of follow-up", "Kuopio, 2315 мужчин, наблюдение 20.7 года"),
   caveat=("HR 0.60 is far outside the range the formula is promised for (0.75–1.3), so the number is inflated. The same journal ran a separate commentary arguing the link may be non-causal: frequent sauna-goers tend to be healthy and not working three jobs already",
           "HR 0.60 далеко за пределами диапазона, для которого формула обещана (0.75–1.3), так что число завышено. В том же журнале вышел отдельный комментарий о том, что связь может быть непричинной: часто парятся те, кто и так здоров и не работает на трёх работах")),
 dict(id="nuts", coef="Coefficients.NUTS", emoji="🥜", conf="STRONG",
   src=("Bao et al., NEJM 2013", "https://www.nejm.org/doi/full/10.1056/NEJMoa1307352"),
   kw="орехи миндаль грецкие фундук nuts almonds",
   label=("A handful of nuts", "Горсть орехов"),
   exposure=("Nuts 7+ times a week against none, HR 0.80", "Орехи 7+ раз в неделю против нуля, HR 0.80"),
   basis=("Harvard cohorts, 118,962 people, with a clean dose-response: under once a week 0.93, two to four times 0.87, daily 0.80",
          "Гарвардские когорты, 118 962 человека, чёткая доза-ответ: реже раза в неделю 0.93, два-четыре раза 0.87, каждый день 0.80"),
   caveat=("Observational, and nuts are eaten by people with money and a habit of watching what they eat. The dose-response is smooth though, which is a good sign",
           "Наблюдательное, и орехи едят люди с деньгами и привычкой следить за едой. Зато доза-ответ ровная, а это хороший признак"),
   dosing=("DAY", 1, "Coefficients.NUTS", "0")),
 dict(id="bike_commute", coef="Coefficients.BIKE_COMMUTE", emoji="🚴", conf="MODERATE",
   src=("Celis-Morales et al., BMJ 2017", "https://www.ccam-tac.org/wp-content/uploads/2020/03/bmj.j1456.full_.pdf"),
   kw="велосипед вело самокат доехал bike cycling commute",
   label=("Cycled instead of driving", "Доехал на велосипеде"),
   exposure=("Commuting to work by bicycle, HR 0.59", "Дорога на работу на велосипеде, HR 0.59"),
   basis=("UK Biobank, 263,450 people, 5 years", "UK Biobank, 263 450 человек, 5 лет"),
   caveat=("The largest plus in the list and the most suspect: HR 0.59 is far outside the formula's range, and people who bike to work are young, healthy and live close by. Treat it as an upper bound",
           "Самый крупный плюс в списке и самый подозрительный: HR 0.59 далеко вне диапазона формулы, а на велосипеде на работу ездят молодые, здоровые и живущие близко. Считай это верхней границей")),
 dict(id="running", coef="Coefficients.RUNNING", emoji="🏃", conf="STRONG",
   src=("Lee et al., JACC 2014", "https://www.jacc.org/doi/10.1016/j.jacc.2014.04.058"),
   kw="бег пробежка кросс run jogging",
   label=("Went for a run", "Пробежка"),
   exposure=("Runners against non-runners, HR 0.70", "Бегуны против небегающих, HR 0.70"),
   basis=("55,137 people, 15 years. Even 5–10 minutes a day gives the same effect as more — the threshold is low",
          "55 137 человек, 15 лет. Даже 5–10 минут в день дают тот же эффект, что и больше — порог низкий"),
   caveat=("HR 0.70 is slightly outside the formula's range. And those who run are those who can: the ill do not run, and die more often",
           "HR 0.70 чуть вне диапазона формулы. И бегают те, кто может бегать: больные не бегают, а умирают чаще")),
 dict(id="fish", coef="Coefficients.FISH", emoji="🐟", conf="ESTIMATE", src=GUIDE,
   kw="рыба лосось селёдка морепродукты fish salmon seafood",
   label=("Fish, one serving", "Рыба, порция"),
   exposure=("A serving of fish in place of red meat", "Порция рыбы вместо порции красного мяса"),
   basis=("Replacing red meat with fish is linked to lower mortality across all the large cohorts. A modest positive figure was taken",
          "Замена красного мяса рыбой связана со снижением смертности во всех крупных когортах. Величина взята небольшой положительной"),
   caveat=(EST_EN, EST_RU)),
 dict(id="sugary_drink", coef="Coefficients.SUGARY_DRINK", emoji="🥤", conf="ESTIMATE", src=GUIDE,
   kw="газировка кола сок сахар лимонад soda sugary",
   label=("Sugary drink", "Сладкая газировка"),
   exposure=("Beyond two cans a week", "Сверх двух банок в неделю"),
   basis=("Sugary drinks are consistently linked to diabetes and mortality. The figure was set slightly below a serving of red meat",
          "Сладкие напитки устойчиво связаны с диабетом и смертностью. Величина взята чуть меньше порции красного мяса"),
   caveat=(EST_EN, EST_RU),
   dosing=("WEEK", 2, "0", "Coefficients.SUGARY_DRINK")),
 dict(id="sweets", coef="Coefficients.SWEETS", emoji="🍬", conf="ESTIMATE", src=GUIDE,
   kw="сладкое десерт шоколад печенье торт sweets dessert",
   label=("Sweets", "Сладкое"),
   exposure=("Beyond one dessert a day", "Сверх одного десерта в день"),
   basis=("A small figure was taken: one dessert a day is background, not a risk factor", "Величина взята небольшой: один десерт в день — это фон, а не фактор риска"),
   caveat=(EST_EN, EST_RU),
   dosing=("DAY", 1, "0", "Coefficients.SWEETS")),
 dict(id="stress", coef="Coefficients.STRESS", emoji="😤", conf="ESTIMATE", src=GUIDE,
   kw="стресс нервы конфликт ссора аврал stress conflict",
   label=("Heavy stress", "Тяжёлый стресс"),
   exposure=("A day of severe stress or conflict", "День сильного стресса или конфликта"),
   basis=("Chronic stress is linked to mortality through the heart and through behaviour. For a single day a small figure was taken",
          "Хронический стресс связан со смертностью через сердце и поведение. Разовый день — величина взята небольшой"),
   caveat=(EST_EN + ". And a one-off stressful day must not be conflated with chronic stress: it is the second that does the damage",
           EST_RU + ". И разовый стресс с хроническим смешивать нельзя: вредит второй")),
 dict(id="reading", coef="Coefficients.READING", emoji="📖", conf="ESTIMATE", src=GUIDE,
   kw="чтение книга читал reading book",
   label=("Half an hour of reading", "Полчаса книги"),
   exposure=("Half an hour of reading books", "Полчаса чтения книг"),
   basis=("There is a well-known Yale study on book readers, but the figure here was set by me to sit beside neighbouring rows",
          "Есть известная работа Йельского университета про читающих книги, но величина здесь назначена мной по порядку соседних строк"),
   caveat=(EST_EN + ". Books are read by the educated and well-off — the effect is almost certainly not from the reading itself",
           EST_RU + ". Читают книги люди с образованием и достатком — эффект почти наверняка не от самого чтения")),
 dict(id="floss", coef="Coefficients.FLOSS", emoji="🦷", conf="ESTIMATE", src=GUIDE,
   kw="нить флосс зубы гигиена floss teeth dental",
   label=("Flossed", "Зубная нить"),
   exposure=("Interdental cleaning for the day", "Чистка межзубных промежутков за день"),
   basis=("Gum disease is linked to cardiovascular mortality. A small figure was taken", "Болезни дёсен связаны с сердечно-сосудистой смертностью. Величина взята маленькой"),
   caveat=(EST_EN + ". Causation is even shakier here than usual: people who look after their teeth look after everything else too",
           EST_RU + ". Причинность тут спорна даже сильнее обычного: за зубами следят те, кто следит и за остальным")),
 dict(id="tea", coef="Coefficients.TEA", emoji="🫖", conf="ESTIMATE", src=GUIDE,
   kw="чай зелёный чёрный tea green",
   label=("Tea", "Чай"),
   exposure=("A cup of tea", "Чашка чая"),
   basis=("By analogy with coffee, but more cautiously: the evidence base is weaker. A third of the coffee figure was taken",
          "По аналогии с кофе, но осторожнее: доказательная база слабее. Взята треть от кофейной величины"),
   caveat=(EST_EN, EST_RU)),
 dict(id="nap", coef="Coefficients.NAP", emoji="😴", conf="ESTIMATE", src=GUIDE,
   kw="дремота сон днём подремал nap daytime",
   label=("Daytime nap", "Дневной сон"),
   exposure=("A short sleep during the day", "Короткий сон днём"),
   basis=("A short nap is usually linked to benefit, a long one to harm. A token figure was taken", "Короткий дневной сон обычно связывают с пользой, длинный — с вредом. Величина взята символической"),
   caveat=(EST_EN + ". Long daytime sleep goes negative in the studies, and that is more a sign of illness than its cause",
           EST_RU + ". Длинный дневной сон в работах уходит в минус, и это скорее признак болезни, чем её причина")),
 dict(id="flu_shot", coef="Coefficients.FLU_SHOT", emoji="💉", conf="ESTIMATE", src=GUIDE,
   kw="прививка вакцина грипп укол flu vaccine shot",
   label=("Flu shot", "Привился от гриппа"),
   exposure=("A seasonal vaccination", "Сезонная прививка"),
   basis=("One of the few rows here backed by randomised trials rather than observation alone. But converting it into minutes of life for a healthy 30-year-old is my estimate",
          "Одна из немногих строк здесь, где есть рандомизированные испытания, а не только наблюдения. Но перевод в минуты жизни для здорового человека 30 лет — моя прикидка"),
   caveat=(EST_EN + ". The bulk of the benefit falls on the elderly and people with chronic illness",
           EST_RU + ". Основная польза приходится на пожилых и людей с хроническими болезнями")),
]
